# Generated by Django 5.2.1 on 2025-05-30 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0001_initial'),
        ('votaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votaciones',
            name='comentario_votacion',
            field=models.CharField(default='defaultXD', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votaciones',
            name='comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votaciones',
            name='descripcion_votacion',
            field=models.CharField(default='defaultXD', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votaciones',
            name='fecha_votacion',
            field=models.DateField(default='2002-08-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votaciones',
            name='imagen_votacion',
            field=models.TextField(default='defaultXD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votaciones',
            name='nombre_votacion',
            field=models.CharField(default='defaultXD', max_length=100),
            preserve_default=False,
        ),
    ]
