# Generated by Django 5.2 on 2025-06-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_votaciones_comentario_votacion_votaciones_comunidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votaciones',
            name='comentario_votacion',
        ),
    ]
