# Generated by Django 5.2 on 2025-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0003_remove_votaciones_comentario_votacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='votaciones',
            name='abierta_votacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='votaciones',
            name='votos_votacion',
            field=models.IntegerField(default=0),
        ),
    ]
