# Generated by Django 5.2 on 2025-06-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_alter_perfil_image_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_noticia', models.CharField(max_length=100)),
                ('fecha_noticia', models.DateField()),
                ('imagen_noticia', models.TextField()),
                ('titular_notica', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_noticia', to='usuarios.perfil')),
            ],
        ),
    ]
