# Generated by Django 5.2 on 2025-06-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0001_initial'),
        ('usuarios', '0003_alter_perfil_image_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anuncio', models.CharField(max_length=100)),
                ('descripcion_anuncio', models.CharField(max_length=100)),
                ('fecha_anuncio', models.DateField()),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
    ]
