# Generated by Django 5.2.1 on 2025-06-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='tipo_anuncio',
            field=models.CharField(choices=[('normal', 'Normal'), ('grave', 'Grave')], default='normal', max_length=20),
        ),
    ]
