# Generated by Django 5.2.1 on 2025-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_anuncio_tipo_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagen_anuncio',
            field=models.TextField(default='lo que sea'),
            preserve_default=False,
        ),
    ]
