# Generated by Django 5.2.1 on 2025-06-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_alter_anuncio_usuario'),
        ('usuarios', '0003_alter_perfil_image_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
    ]
