# Generated by Django 5.2.1 on 2025-06-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_comentarioforo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentarioForo',
        ),
    ]
