# Generated by Django 5.2.1 on 2025-05-30 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0001_initial'),
        ('usuarios', '0003_alter_perfil_image_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporte', models.CharField(max_length=100)),
                ('descripcion_reporte', models.CharField(max_length=100)),
                ('fecha_reporte', models.DateField()),
                ('direccion_reportes', models.CharField(max_length=100)),
                ('imagen_reporte', models.TextField()),
                ('gravedad_reporte', models.CharField(choices=[('LEVE', 'Leve'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=40)),
                ('comentario_reporte', models.CharField(max_length=100)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reporte', to='usuarios.perfil')),
            ],
        ),
    ]
