# Generated by Django 5.2.1 on 2025-06-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reportes_estado_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='fecha_reporte',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='imagen_reporte',
            field=models.TextField(null=True),
        ),
    ]
