# Generated by Django 5.2.1 on 2025-05-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_alter_perfil_image_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campana', models.CharField(max_length=100)),
                ('descripcion_campana', models.CharField(max_length=100)),
                ('direccion_campana', models.CharField(max_length=100)),
                ('fecha_campana', models.DateField()),
                ('imagen_campana', models.TextField()),
                ('comentario_campana', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
    ]
