# Generated by Django 5.2.1 on 2025-05-30 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0001_initial'),
        ('comunidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidades'),
            preserve_default=False,
        ),
    ]
