# Generated by Django 5.2.1 on 2025-06-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0002_campana_comunidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='comentario_campana',
        ),
    ]
