# Generated by Django 5.2.1 on 2025-06-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0003_remove_campana_comentario_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='apoyos',
            field=models.IntegerField(default=0),
        ),
    ]
