# Generated by Django 5.2.1 on 2025-06-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0005_remove_campana_apoyos_apoyo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoyo',
            name='comunidad',
        ),
    ]
