# Generated by Django 5.2.1 on 2025-06-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0006_remove_apoyo_comunidad'),
        ('usuarios', '0003_alter_perfil_image_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyo',
            name='cantidad_apoyo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='apoyo',
            unique_together={('usuario', 'campana')},
        ),
    ]
