# Generated by Django 5.2.1 on 2025-05-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_cedula_usuario_perfil_image_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
