# Generated by Django 5.2.1 on 2025-05-30 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0001_initial'),
        ('usuarios', '0003_alter_perfil_image_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_peticion', models.CharField(max_length=100)),
                ('descripcion_peticion', models.CharField(max_length=100)),
                ('fecha_peticion', models.DateField()),
                ('imagen_peticion', models.TextField()),
                ('comentario_peticion', models.CharField(max_length=100)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_peticiones', to='usuarios.perfil')),
            ],
        ),
    ]
