# Generated by Django 5.2.1 on 2025-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peticiones',
            name='comentario_peticion',
        ),
        migrations.RemoveField(
            model_name='peticiones',
            name='imagen_peticion',
        ),
        migrations.AddField(
            model_name='peticiones',
            name='estado_peticion',
            field=models.CharField(choices=[('rechazada', 'RECHAZADA'), ('pendiente', 'PENDIENTE'), ('aprobada', 'APROBADA')], default='pendiente', max_length=50),
        ),
    ]
